### ISSUE TITLE
url('~@/assets/...') in css doesn't work after build

### ISSUE THREAD

**Issue by franciscolourenco** [adambullmer/vue-cli-plugin-browser-extension#39]
Related: https://github.com/vuejs/vue-cli/issues/4197

One way of fixing this would be to use the `filename` option, or to place the flatten the structure at build time.

**Comment by adambullmer** [comment]
While doing some hunting around, I happened upon this idea from some best practices with using the extension ID. Put your static assets somewhere in your `public/` directory and reference them with the dynamic absolute URL to your extension:

```css
body {
  background-image:url('chrome-extension://__MSG_@@extension_id__/background.png');
}
```

The downside is you're now just direct copying over your images into the build instead of letting webpack handle them.
